logging:
  level:
    org.springframework: ERROR
    com.weiss.weissdata: INFO
  file: file-storage.log
server:
  port: 8083
spring:
  application:
    name: file-storage
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/